name: Deploy Production
on:
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x] # 実行するノードバージョン
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
        working-directory: ./app
      - name: npm run build
        run: npm run build
        working-directory: ./app
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: publish
          FOLDER: ./app/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
